### ISSUE TITLE
Performance comparison

### ISSUE THREAD

**Issue by mundschenk-at** [mikerockett/php-typeset#1]
@mikerockett, have you already been able to a performance comparison between this and php-typography? (To be fair, only comparable features should be enabled.)

I've the feeling that the heavy processing lies in the use of regex replacements, but if phpQuery is faster than direct DOM walking, it would be good to know.  I'm keen to gain some insights from your project to improve the performance of php-typography (e.g. maybe some uses of regexes could be replaced by clever applications of `str_replace`).

**Comment by mikerockett** [comment]
I haven't done any performance-tests yet. From typical experience, this does appear to be quicker, but it could well differ in certain cases.

I have also had a look at the use of expressions here - for the most part, all I've done at the moment is port Typeset from Javascript and added a feature here and there (and removed one, and disabled a few others). Now that the general structure of the library is in place, I'm going to spend a little time over the next day or so seeing what can and cannot be improved, using whatever knowledge I have. I'm not a pro at this kind of thing, so would be very happy to receive input on this front. (There are some notes here and there about switching to str_replace as well. In some cases, it's either unavoidable, or I simply don't have the needed skill to switch it over to something more elaborate for the sake of performance.) I did notice that in php-typography, there's quite a bit of escaping and unescaping going on, and was curious to know if any of that could be avoided. David appears to have only done it in some places, were it was needed most. That said, I haven't looked into this properly - in fact, I haven't thoroughly reviewed php-typography to see how it works.

One of the issues that David brings up in his version is that there is recursion in `findTextNodes` - I think I know what's going on there, but had thought it was intentional in order to sweep through the DOM.

The reason I chose phpQuery was simple: I needed something that would best emulate the cheerio/jQuery methodology in PHP. There appear to be quite a few libraries that can do this, and phpQuery seems to fit best in this instance. However, the original library appears to have been abandoned, and I'm not using the most recent fork of it that I can find. Considering that it was used for the purposes of a successful port, I'm willing to look at other ways of going about this, now that a library-structure is in place, especially from an OOP perspective. However, I would only be keen on doing that for the sake of performance - otherwise, it would be a waste of time (unless there would be a considerable learning curve in it for me and performace would not be hindered).

**Comment by mikerockett** [comment]
Oh, and just a note about phpQuery: I haven't reviewed it either, but I do believe it is a wrapper for dom-document. So from a performance standpoint, it would add to the processing-time.

**Comment by mundschenk-at** [comment]
In php-typography, I'm using XPath. It's much less intuitive than jQuery syntactically, but has the benefit of being built into PHP, so I'm assuming it's faster than a pure PHP library sitting on top of the DOM. 

The problem with the native PHP DOMDocument is that it is based on libXML and not working that well with newer HTML5 documents. HTML5-PHP solves that problem, but parsing HTML is decidedly non-trivial. 

Some time ago, I did some profiling on php-typography and besides parsing, hyphenation is by far the most resource heavy part. I tried to speed that up a bit by changing the algorithm to use a "trie" data structure, but I'm not sure the improvements are actually notable (or even really there at all).

**Comment by mikerockett** [comment]
Once I fully understand what's going on with phpQuery and how it all works, I'll have a look-see at html5-php. If it improves performance, then I'm happy to implement it.

Another thing to know is that I'm no typography expert. For all I know, the module orders could be wrong, and certain practices may not be correct (for example, with the dashes in their different contexts). For the most part, however, I am quite pleased with the outcome of this porting exercise - was quite fun (first port I've ever done).

> Some time ago, I did some profiling on php-typography and besides parsing, hyphenation is by far the most resource heavy part. I tried to speed that up a bit by changing the algorithm to use a "trie" data structure, but I'm not sure the improvements are actually notable (or even really there at all).

I'd be interested to know how similar your hyphenator is in comparison to [Hypher](https://github.com/bramstein/hypher), especially from a performance standpoint. I'm sure their implementations and dictionaries are quite different. The technicalities behind both implementations (hyphenation in general, hehe) are beyond me.

**Comment by mundschenk-at** [comment]
I'm not sure html5-php will be faster. It just produces better/more correct results with HTML5 than plain `DOMDocument` - I haven't delved deeply enough into phpQuery to see if they work around the limitations of the builtin DOM support.

Regrading hyphenation, all the widely available libraries are based on the TeX algorithm and dictionaries, so any differences are more a question of representation rather than anything else.

**Comment by mikerockett** [comment]
I see - well we'd only know if we tried. As a brief performance indicator, a small document of smallish 6 paragaphs takes around 200ms to process with all modules enabled. The small caps module seems to take a considerable chunk of that, depending on how many words appear within a node or chunk thereof. As you'll see in the module, it splits the node up into words, removes unnecessary stuff, and then wraps the necessaries in spans. If I have the basic modules enabled (no styling, etc.) then I remember an average of 50-70ms (approx.) - I'd be happier with proper performance tests on a different variety of documents. I'd also like to do some tests from a text-formatter point-of-view, where the library will be called, say, ten times for a blog's home page.

I see - thanks for the clarification.

**Comment by mikerockett** [comment]
I've started doing some actual benchmarks (comparitive features enabled). So far, it does actually look like Typography is faster. I'll post the results once I've finished the benchmarking.

**Comment by mikerockett** [comment]
Here's a simple benchmarker. Quick results if you don't want to download it:

```
PHP Typeset (excluding Ligatures and SimpleMath)

 - 1-4400w-12p = 0.452s
 - 10-100w-12p = 0.045s
 - 2-3800w-12p = 0.379s
 - 3-3200w-12p = 0.330s
 - 4-2600w-12p = 0.278s
 - 5-2000w-12p = 0.226s
 - 6-1400w-12p = 0.182s
 - 7-800w-12p = 0.130s
 - 8-400w-12p = 0.097s
 - 9-200w-12p = 0.069s

Typeset took 2.188 seconds to convert all files (peak mem. = 2MiB).

PHP Typography (comparative)

 - 1-4400w-12p = 0.427s
 - 10-100w-12p = 0.008s
 - 2-3800w-12p = 0.314s
 - 3-3200w-12p = 0.264s
 - 4-2600w-12p = 0.230s
 - 5-2000w-12p = 0.165s
 - 6-1400w-12p = 0.115s
 - 7-800w-12p = 0.065s
 - 8-400w-12p = 0.032s
 - 9-200w-12p = 0.015s

Typographer took 1.634 seconds to convert all files (peak mem. = 4MiB).
```

Each example is named according to how many words and paragraphs it has (`*w` and `*p`), and I only did 12 paragraphs. Mem. usage didn't appear to differ, both at 2M.

So, from a performance standpoint, Typographer is faster. Perhaps some deeper benchmarking is in order, when I get the time.

(Sorry, I see now the sorting isn't right...)

Attached: **[benchmarking.zip](https://github.com/mikerockett/php-typeset/files/691429/benchmarking.zip)**

**Comment by mikerockett** [comment]
Apologies, those benchmarks are slightly off. Typography doesn't have the symbols module I implemented, which does numeros, silcrows (single and double), and interrobangs. After disabling that module, it shaves between 100ms and 200ms from the time.

My hanging punctuation module, which incorporates your `initial_quotes` and `style_hanging_punctuation` is quite resource intensive. Once disabled on my side, an additional 500ms is shaved off. So I think this is one of the primary culprits. Turning it off on Typography doesn't appear to make a difference.

Using Typeset with everything at default:

```
 - 01-4400w-12p = 0.098s
 - 02-3800w-12p = 0.070s
 - 03-3200w-12p = 0.069s
 - 04-2600w-12p = 0.068s
 - 05-2000w-12p = 0.057s
 - 06-1400w-12p = 0.050s
 - 07-800w-12p = 0.051s
 - 08-400w-12p = 0.044s
 - 09-200w-12p = 0.034s
 - 10-100w-12p = 0.028s
```

Those figures are with the following modules disabled (default setting):

- SmallCaps (also quote the culprit)
- HangingPunctuation
- Ligatures
- SimpleMath
- Symbols

**Comment by mikerockett** [comment]
Bumped into JoliTypo, and have done one more benchmark with basic features only:

```
PHP Typeset (Punctuation, Quotes, Spaces)

 - 01-4400w-12p = 0.065s
 - 02-3800w-12p = 0.043s
 - 03-3200w-12p = 0.039s
 - 04-2600w-12p = 0.036s
 - 05-2000w-12p = 0.031s
 - 06-1400w-12p = 0.028s
 - 07-800w-12p = 0.025s
 - 08-400w-12p = 0.023s
 - 09-200w-12p = 0.019s
 - 10-100w-12p = 0.016s

Typeset took 0.327 seconds to convert all files (mem. = 2MiB).

PHP Typography (smart_quotes, dashes, ellipses, dash_spacing, space_collapse)

 - 01-4400w-12p = 0.375s
 - 02-3800w-12p = 0.315s
 - 03-3200w-12p = 0.260s
 - 04-2600w-12p = 0.209s
 - 05-2000w-12p = 0.211s
 - 06-1400w-12p = 0.113s
 - 07-800w-12p = 0.062s
 - 08-400w-12p = 0.030s
 - 09-200w-12p = 0.015s
 - 10-100w-12p = 0.008s

Typographer took 1.598 seconds to convert all files (mem. = 2MiB).

JoliTypo (CurlyQuote, Dash, Ellipses, and SmartQuotes)

 - 01-4400w-12p = 0.004s
 - 02-3800w-12p = 0.002s
 - 03-3200w-12p = 0.002s
 - 04-2600w-12p = 0.002s
 - 05-2000w-12p = 0.001s
 - 06-1400w-12p = 0.001s
 - 07-800w-12p = 0.001s
 - 08-400w-12p = 0.000s
 - 09-200w-12p = 0.000s
 - 10-100w-12p = 0.000s

JoliTypo took 0.014 seconds to convert all files (mem. = 2MiB).
```

Of course, the basic features are not identical in behaviour, but interesting to look at nonetheless.

**Comment by mundschenk-at** [comment]
I know about JoliTypo, but it's interesting that it is so much faster. I'll have a look at how they do their iteration over the nodes.

**Comment by mikerockett** [comment]
Have just pushed an update that changes a few things. In terms of performance, [SmallCaps](https://github.com/mikerockett/php-typeset/blob/master/src/Typeset/Module/Modules/SmallCaps.php) now uses the method found in your PHP Typography - I simply couldn't find anything more efficient or faster. (Your package is attributed in the readme and code).

**Comment by mundschenk-at** [comment]
Ah, you should credit Jeffrey D. King mostly, the regular expression is still almost completely his work. Did you test with `\L{u}` instead? Doing a comparison test between the two regex variants has been on my mental to-do list since forever. The original reason for doing a custom regex is not valid anymore, as the whole package needs full unicode support nowadays.

**Comment by mikerockett** [comment]
I see - will do that soon. Haven't tested that - though I'm not 100% sure how much more of a benefit that would be over what's in place at the moment? Wish I was a regex pro!

**Comment by mikerockett** [comment]
PCRE doesn't seem to support it:

> Compilation failed: PCRE does not support \L, \l, \N{name}, \U, or \u

**Comment by mundschenk-at** [comment]
Sorry, I meant `\p{Lu}`.

**Comment by mikerockett** [comment]
Ah, of course -- will give that a try.

**Comment by mikerockett** [comment]
Looks like that works correctly on my side, though I don't have an extensive test-string to test it with, but I think it's doing the job correctly; after-all it is meant to match any unicode letter that has a lower-case variant. I think I'll switch to this for Typeset.

**Comment by mundschenk-at** [comment]
@mikerockett I've refactored the PHP-Typography API and released it as a standalone library (also available via Composer): [mundschenk-at/php-typography](https://github.com/mundschenk-at/php-typography).

**Comment by mikerockett** [comment]
Thank you! Will look into it soon, and upgrade https://github.com/rockettpw/textformatter-typographer

**Comment by mikerockett** [comment]
Typeset is now retired: 1bbf62b
